//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiberrySelf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryBD1 : DbContext
    {
        public LibraryBD1()
            : base("name=LibraryBD1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
