//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiberrySelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int RentalID { get; set; }
        public int LibrarianID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> OperarionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Librarian Librarian { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
